name: Move assigned issues and review requests

on:
  issues:
    types: [assigned]
  pull_request:
    types: [review_requested]

jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    steps: 
      - name: Run if the assignee is set as the user
        if: github.event.issues.assignee == 'marianamarasoiu' || github.event.pull_request.requested_reviewers.contains('marianamarasoiu')
        uses: alex-page/github-project-automation-plus@v0.1.2
        with:
          project: Mariana
          column: To do
          repo-token: ${{ secrets.GITHUB_TOKEN }}
